# This is a basic workflow to help you get started with Actions
 
name: 打包发布
 
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    tags:
      - 'v*.*.*'
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # job's id
  release:
    # job's name
    name: 打包发布应用
    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}
    # create a build matrix for jobs
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
    # create steps
    steps:
      # step1: check out repository
      - name: 拉取代码
        uses: actions/checkout@v2
 
      # step2: install node env
      - name: 安装 Node.js
        uses: actions/setup-node@v2-beta
 
      # step3: npm install
      - name: npm install
        run: |
          npm install
      # step3: npm install
      - name: 输出参数
        run: |
          echo mac_certs
        env:
          mac_certs: ${{ secrets.MAC_CERTS }}
          mac_certs_password: ${{ secrets.MAC_CERTS_PASSWORD }}
      # step4: build app for mac/win
      - name: 打包应用（macOS）
        if: startsWith(matrix.os, 'macos')
        # uses: samuelmeuli/action-electron-builder@v1.6.0
        # with:
        #   github_token: ${{ secrets.GITHUB_TOKEN }}
        #   mac_certs: ${{ secrets.MAC_CERTS }}
        #   mac_certs_password: ${{ secrets.MAC_CERTS_PASSWORD }}
        run: |
          npm run pack
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.MAC_CERTS }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
      
      - name: 打包应用（Windows）
        if: startsWith(matrix.os, 'windows')
        run: |
          npm run pack
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
      - name: 上传构建产物
        uses: LabhanshAgrawal/upload-artifact@v3
        with:
          path: |
            dist/*.dmg
            dist/*.exe
            dist/*.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 发布 Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.dmg
            dist/*.exe
            dist/*.zip
            dist/latest.yml
            dist/latest-mac.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}